# This rule is not used by the project llm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over llm.geeper.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: llm-operator
    app.kubernetes.io/managed-by: kustomize
  name: deployment-admin-role
rules:
- apiGroups:
  - llm.geeper.io
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - llm.geeper.io
  resources:
  - deployments/status
  verbs:
  - get
