# A viewer role, containing permissions a viewer would need.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollama-deployment-viewer-role
rules:
- apiGroups:
  - llm.geeper.io
  resources:
  - ollamadeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llm.geeper.io
  resources:
  - ollamadeployments/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
