import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Chat & Interaction',
      items: ['chat/openwebui', 'chat/rag', 'chat/tools'],
    },
    {
      type: 'category',
      label: 'Coding Assistants',
      items: ['coding-assistants/continue-dev', 'coding-assistants/tabby'],
    },
    'installation',
    'usage',
    {
      type: 'category',
      label: 'API Reference',
      items: ['crd-reference'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/deployment', 'guides/configuration'],
    },
  ],
   */
};

export default sidebars;
