apiVersion: llm.geeper.io/v1alpha1
kind: LMDeployment
metadata:
  name: dev-ollama
  namespace: development
spec:
  ollama:
    replicas: 1
    image: ollama/ollama
    imageTag: latest
    service:
      type: NodePort
      port: 11434
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    models:
      - "llama2:7b"
  
  openwebui:
    enabled: true
    replicas: 1
    image: ghcr.io/open-webui/open-webui
    imageTag: main
    service:
      type: NodePort
      port: 8080
    ingress:
      enabled: false
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
