apiVersion: llm.geeper.io/v1alpha1
kind: LMDeployment
metadata:
  name: openwebui-with-auto-langfuse
  namespace: default
  labels:
    app: openwebui-with-auto-langfuse
    component: ai-chat-with-monitoring
spec:
  ollama:
    models:
      - "gemma3:270m"
  openwebui:
    enabled: true
    replicas: 1
    image: ghcr.io/open-webui/open-webui:main
    ingress:
      host: openwebui.localhost
    langfuse:
      enabled: true
      debug: false
      projectName: "openwebui-project"
      environment: "development"
      deploy:
        image: langfuse/langfuse:3.75.2
        replicas: 1
        port: 3000
        serviceType: ClusterIP
        hostname: "0.0.0.0"
        basePath: ""
        runtime: "nodejs"
        sharpPath: "/app/node_modules/sharp"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        persistence:
          enabled: true
          size: "10Gi"
        ingress:
          host: langfuse.localhost
        envVars:
          # Database configuration - using external PostgreSQL and ClickHouse
          - name: DATABASE_URL
            value: "postgres://langfuse:langfuse@postgres:5432/langfuse"
          - name: CLICKHOUSE_CLUSTER_ENABLED
            value: "false"
          - name: CLICKHOUSE_URL
            value: "http://clickhouse:8123"
          - name: CLICKHOUSE_MIGRATION_URL
            value: "clickhouse://clickhouse:9000"
          - name: CLICKHOUSE_USER
            value: "default"
          - name: CLICKHOUSE_PASSWORD
            value: "langfuse-clickhouse-password"
          # Authentication configuration
          - name: NEXTAUTH_SECRET
            value: "langfuse-next-secret"
          - name: SALT
            value: "langfuse-next-salt"
          - name: ENCRYPTION_KEY
            value: "c696b2d7f26042011ae76cfe94bdae305faeed4ae0f172c0939d0d17a0789234"
          # Storage configuration
          - name: STORAGE_PROVIDER
            value: "local"
          - name: STORAGE_LOCAL_PATH
            value: "/app/data"
        # Topology spread constraints for high availability
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: langfuse
