# This ConfigMap is automatically created by the controller
# when you define plugins in your deployment spec
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-with-tools-openwebui-config
  namespace: default
  labels:
    app: openwebui
    llm-deployment: ollama-with-tools
data:
  config.json: |
    {
      "version": 0,
      "ui": {
        "enable_signup": false
      },
      "openai": {
        "enable": false,
        "api_base_urls": ["https://api.openai.com/v1"],
        "api_keys": [""],
        "api_configs": {
          "0": {}
        }
      },
      "tool_server": {
        "connections": [
          {
            "url": "http://ollama-with-tools-plugin-weather-tool:8081",
            "path": "openapi.json",
            "auth_type": "bearer",
            "key": "",
            "config": {
              "enable": true,
              "access_control": {
                "read": {
                  "group_ids": [],
                  "user_ids": []
                },
                "write": {
                  "group_ids": [],
                  "user_ids": []
                }
              }
            },
            "info": {
              "name": "weather-tool",
              "description": "openapi tool for ollama-with-tools"
            }
          },
          {
            "url": "http://ollama-with-tools-plugin-document-tool:8082",
            "path": "openapi.json",
            "auth_type": "none",
            "key": "",
            "config": {
              "enable": true,
              "access_control": {
                "read": {
                  "group_ids": [],
                  "user_ids": []
                },
                "write": {
                  "group_ids": [],
                  "user_ids": []
                }
              }
            },
            "info": {
              "name": "document-tool",
              "description": "custom tool for ollama-with-tools"
            }
          },
          {
            "url": "http://ollama-with-tools-plugin-github-tool:8083",
            "path": "openapi.json",
            "auth_type": "bearer",
            "key": "",
            "config": {
              "enable": true,
              "access_control": {
                "read": {
                  "group_ids": [],
                  "user_ids": []
                },
                "write": {
                  "group_ids": [],
                  "user_ids": []
                }
              }
            },
            "info": {
              "name": "github-tool",
              "description": "openapi tool for ollama-with-tools"
            }
          }
        ]
      }
    }
