---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-credentials
  namespace: default
type: Opaque
stringData:
  LANGFUSE_PUBLIC_KEY: "your-langfuse-public-key"
  LANGFUSE_SECRET_KEY: "your-langfuse-secret-key"
---
apiVersion: llm.geeper.io/v1alpha1
kind: LMDeployment
metadata:
  name: openwebui-with-langfuse
  namespace: default
spec:
  ollama:
    models:
      - "llama3.2:1b"
      - "gemma3:270m"
  
  openwebui:
    enabled: true
    image: ghcr.io/open-webui/open-webui:main
    replicas: 1
    service:
      type: ClusterIP
      port: 8080

    langfuse:
      enabled: true
      url: "https://cloud.langfuse.com"  # External Langfuse instance
      projectName: "my-openwebui-project"
      environment: "production"
      secretRef:
        name: "langfuse-credentials"  # Reference to the secret above
        namespace: "default"